# Generated by Django 5.1.5 on 2025-01-14 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'MRole',
                'db_table': 'employee_mrole',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roleassign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.mrole')),
            ],
            options={
                'verbose_name_plural': 'Roleassign',
                'db_table': 'employee_roleassign',
                'managed': True,
            },
        ),
    ]
